import { ACTIVE_KEY,deleteFootprint,getFootprint,listFootprints,newId,putFootprint } from "./footprint-storage.js";
import { APP_VERSION,FILE_SCHEMA_VERSION,SCORING_VERSION,downloadBlob,validateBeforeExport,validateImport } from "./footprint-io.js";
import { calculateStatistics } from "./statistics.js";
import { buildXlsxBlob } from "./excel-export.js";

const NS="http://www.w3.org/2000/svg", $=s=>document.querySelector(s);
const reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;
const map=$("#network-map"),stage=$("#map-stage"),viewport=$("#map-viewport"),artwork=$("#artwork-layer"),segments=$("#segment-layer"),stations=$("#station-layer"),eggs=$("#easter-egg-layer"),handles=$("#interaction-layer"),tooltip=$("#map-tooltip"),loading=$("#loading-state"),status=$("#dataset-status"),zoomText=$("#zoom-readout");
let view={x:0,y:0,scale:1},initial={...view},minScale=.1,maxScale=12,pointers=new Map(),dragStart=null,pinchStart=null;
const FOOTPRINT_KEY="beijing-rail-footprint-ui-v1";
let footprint=(()=>{try{const saved=JSON.parse(localStorage.getItem(FOOTPRINT_KEY)||"{}");return{visited:new Set(saved.visitedStationIds||[]),ridden:new Set(saved.riddenSegmentIds||[]),visitTypes:new Map()}}catch{return{visited:new Set(),ridden:new Set(),visitTypes:new Map()}}})();
let currentNetwork=null,currentHotspots=null,currentRecord=null,pendingSave=null,historyPast=[],historyFuture=[];
const el=(name,attrs={})=>{const n=document.createElementNS(NS,name);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n};
function applyView(){viewport.setAttribute("transform",`translate(${view.x} ${view.y}) scale(${view.scale})`);const ratio=view.scale/initial.scale;zoomText.textContent=`${Math.round(ratio*100)}%`;map.classList.toggle("show-labels",ratio>=1.7)}
const screenPoint=e=>{const r=map.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
function zoomAt(p,f){const next=Math.max(minScale,Math.min(maxScale,view.scale*f)),r=next/view.scale;view.x=p.x-(p.x-view.x)*r;view.y=p.y-(p.y-view.y)*r;view.scale=next;applyView()}
function fit(width,height){const r=map.getBoundingClientRect(),pad=Math.min(r.width,r.height)*.055,scale=Math.min((r.width-pad*2)/width,(r.height-pad*2)/height);initial={scale,x:(r.width-width*scale)/2,y:(r.height-height*scale)/2};minScale=scale*.72;maxScale=scale*16;view={...initial};applyView()}
const now=()=>new Date().toISOString();
function recordFile(record=currentRecord){return{schemaVersion:FILE_SCHEMA_VERSION,datasetVersion:currentNetwork?.meta.datasetVersion||"2026.06.30.1",scoringVersion:SCORING_VERSION,appVersion:APP_VERSION,title:record?.title||"我的足迹",selectedSegmentIds:[...footprint.ridden],stationVisits:[...footprint.visited].map(stationId=>({stationId,visitTypes:footprint.visitTypes.get(stationId)||defaultVisitTypes(stationId)})),createdAt:record?.createdAt||now(),updatedAt:now()}}
function defaultVisitTypes(stationId){const symbol=currentHotspots?.stationHotspots.find(x=>x.stationId===stationId)?.symbol;return[symbol==="out_of_station_transfer"?"out_of_station_transfer":symbol==="in_station_transfer"?"in_station_transfer":"board_or_alight"]}
function saveFootprint(){if(!currentRecord)return;const id=currentRecord.id,snapshot={...currentRecord,...recordFile(currentRecord),id};if(pendingSave)clearTimeout(pendingSave.timer);pendingSave={id,snapshot,timer:setTimeout(async()=>{const job=pendingSave;if(!job||job.id!==id)return;pendingSave=null;await putFootprint(job.snapshot);if(currentRecord?.id===id){currentRecord=job.snapshot;setFileStatus("已自动保存","success");refreshFootprintSelect()}},250)}}
async function flushPendingSave(){if(!pendingSave)return;const job=pendingSave;clearTimeout(job.timer);pendingSave=null;await putFootprint(job.snapshot);if(currentRecord?.id===job.id)currentRecord=job.snapshot}
function toggle(set,id){set.has(id)?set.delete(id):set.add(id)}
function snapshotState(){return{ridden:[...footprint.ridden],visited:[...footprint.visited],visitTypes:[...footprint.visitTypes].map(([id,types])=>[id,[...types]])}}
function restoreState(state){footprint={ridden:new Set(state.ridden),visited:new Set(state.visited),visitTypes:new Map(state.visitTypes.map(([id,types])=>[id,[...types]]))}}
function recordHistory(){historyPast.push(snapshotState());if(historyPast.length>100)historyPast.shift();historyFuture=[];updateHistoryButtons()}
function updateHistoryButtons(){$("#undo-action").disabled=!historyPast.length;$("#redo-action").disabled=!historyFuture.length}
function refreshAfterStateChange(){saveFootprint();render(currentNetwork,currentHotspots,true);updateHistoryButtons()}
function showTip(e,title,detail){tooltip.innerHTML=`<strong>${title}</strong>${typeof detail==="function"?detail():detail}`;tooltip.hidden=false;const pad=12,x=e.clientX||innerWidth/2,y=e.clientY||innerHeight/2,box=tooltip.getBoundingClientRect();tooltip.style.left=`${Math.max(pad,Math.min(x,innerWidth-box.width-pad-12))}px`;tooltip.style.top=`${Math.max(pad,Math.min(y,innerHeight-box.height-pad-12))}px`}
function interactive(node,title,detail,onToggle){node.addEventListener("pointerenter",e=>showTip(e,title,detail));node.addEventListener("pointermove",e=>showTip(e,title,detail));node.addEventListener("pointerleave",()=>tooltip.hidden=true);node.addEventListener("focus",e=>showTip(e,title,detail));node.addEventListener("blur",()=>tooltip.hidden=true);node.addEventListener("click",e=>{e.stopPropagation();onToggle();showTip(e,title,detail)})}
const percent=(part,total)=>total?`${(part/total*100).toFixed(1)}%`:"0.0%";
function renderStatistics(network){
 const stats=calculateStatistics(network,recordFile()),coverage=stats.lines.map(x=>({line:x.line,index:x.index,count:x.segmentCount,total:x.segmentTotal,rate:x.segmentRate,stationCount:x.stationCount,stationTotal:x.stationTotal,stationRate:x.stationRate})),districtStats=stats.districts;
 const set=(id,value)=>{const node=document.querySelector(id);if(node)node.textContent=value};
 set("#stat-score",stats.points.total);set("#stat-mileage",`${(stats.mileageM/1000).toFixed(3)} km`);set("#stat-stations",`${stats.visited.length}/${network.stations.length}`);set("#stat-segments",`${stats.riddenIds.length}/${network.segments.length}`);set("#stat-lines",`${stats.participatedLines.length}/${network.lines.length}`);set("#stat-complete-lines",`${stats.completedLines.length}/${network.lines.length}`);set("#stat-districts",`${stats.visitedDistrictIds.size}/${network.districts.length}`);set("#stat-transfers",`${stats.visitedTransfers}/${stats.transferStationIds.size}`);
 set("#rate-stations",percent(stats.visited.length,network.stations.length));set("#rate-segments",percent(stats.riddenIds.length,network.segments.length));set("#rate-mileage",percent(stats.mileageM,stats.totalMileageM));set("#rate-lines",percent(stats.participatedLines.length,network.lines.length));set("#rate-complete",percent(stats.completedLines.length,network.lines.length));set("#rate-districts",percent(stats.visitedDistrictIds.size,network.districts.length));set("#rate-transfers",percent(stats.visitedTransfers,stats.transferStationIds.size));
 set("#score-detail",`里程 ${stats.points.mileage} · 车站 ${stats.points.stations} · 换乘 ${stats.points.transfers} · 行政区 ${stats.points.districts} · 全线 ${stats.points.lines}`);set("#stat-top-line",stats.topLines.length?stats.topLines.map(x=>`${x.line.nameZh} ${x.segmentCount}/${x.segmentTotal}`).join("、"):"—");set("#stat-top-station-line",stats.topStationLines.length?stats.topStationLines.map(x=>`${x.line.nameZh} ${x.stationCount}/${x.stationTotal}`).join("、"):"—");set("#stat-top-district",stats.topDistricts.length?stats.topDistricts.map(x=>`${x.district.nameZh} ${x.count}站`).join("、"):"—");
 const lineSort=$("#line-stats-sort")?.value||"station-count",lineComparators={"station-count":(a,b)=>b.stationCount-a.stationCount||b.stationRate-a.stationRate,"station-rate":(a,b)=>b.stationRate-a.stationRate||b.stationCount-a.stationCount,"segment-count":(a,b)=>b.count-a.count||b.rate-a.rate,"segment-rate":(a,b)=>b.rate-a.rate||b.count-a.count,name:(a,b)=>a.index-b.index};coverage.sort((a,b)=>lineComparators[lineSort](a,b)||a.index-b.index);$("#line-stats-list").innerHTML=coverage.map(x=>`<article><strong>${x.line.nameZh}</strong><span>车站 ${x.stationCount}/${x.stationTotal} · ${percent(x.stationCount,x.stationTotal)}</span><span>区间 ${x.count}/${x.total} · ${percent(x.count,x.total)}</span></article>`).join("");
 const districtSort=$("#district-stats-sort")?.value||"count",districtComparators={count:(a,b)=>b.count-a.count||b.rate-a.rate,rate:(a,b)=>b.rate-a.rate||b.count-a.count,name:(a,b)=>a.district.nameZh.localeCompare(b.district.nameZh,"zh-CN")};districtStats.sort((a,b)=>districtComparators[districtSort](a,b)||a.district.nameZh.localeCompare(b.district.nameZh,"zh-CN"));$("#district-stats-list").innerHTML=districtStats.map(x=>`<article><strong>${x.district.nameZh}</strong><span>${x.count}/${x.total} 站 · ${percent(x.count,x.total)}</span></article>`).join("");
 const names=x=>x.stations.length?x.stations.map(s=>s.nameZh).join("、"):"—";set("#extreme-north",names(stats.extremes.north));set("#extreme-south",names(stats.extremes.south));set("#extreme-east",names(stats.extremes.east));set("#extreme-west",names(stats.extremes.west));set("#span-ns",stats.extremes.northSouthKm===null?"—":`${stats.extremes.northSouthKm.toFixed(1)} km`);set("#span-ew",stats.extremes.eastWestKm===null?"—":`${stats.extremes.eastWestKm.toFixed(1)} km`);$("#statistics-panel").hidden=false;
}
$("#line-stats-sort").addEventListener("change",()=>currentNetwork&&renderStatistics(currentNetwork));$("#district-stats-sort").addEventListener("change",()=>currentNetwork&&renderStatistics(currentNetwork));
function render(network,hotspots,preserveView=false){
 currentNetwork=network;currentHotspots=hotspots;
 const lineById=new Map(network.lines.map(x=>[x.id,x])),stationById=new Map(network.stations.map(x=>[x.id,x])),lsById=new Map(network.lineStations.map(x=>[x.id,x])),segmentById=new Map(network.segments.map(x=>[x.id,x])),pointByStationId=new Map(hotspots.stationHotspots.map(x=>[x.stationId,x])),stationLines=new Map();
 for(const item of network.lineStations){if(!stationLines.has(item.stationId))stationLines.set(item.stationId,new Map());stationLines.get(item.stationId).set(item.lineId,lineById.get(item.lineId))}
 artwork.replaceChildren();const sf=document.createDocumentFragment();
 const stationIdByName=new Map(network.stations.map(x=>[x.nameZh,x.id])),eggRules=[{id:"tiananmen",names:["天安门西","天安门东"],href:"./assets/easter-egg-tiananmen.png",x:942,y:638,width:75,height:22,label:"天安门彩蛋"},{id:"capital-airport",names:["2号航站楼","3号航站楼"],href:"./assets/easter-egg-airport.png",x:1490,y:225,width:40,height:40,label:"首都机场彩蛋"},{id:"daxing-airport",names:["大兴机场"],href:"./assets/easter-egg-airport.png",x:990,y:1150,width:40,height:40,label:"大兴机场彩蛋"}],eggNodes=new Map();for(const rule of eggRules){const image=el("image",{href:rule.href,x:rule.x,y:rule.y,width:rule.width,height:rule.height,class:"easter-egg",role:"img","aria-label":rule.label});image.hidden=true;eggNodes.set(rule.id,image)}eggs.replaceChildren(...eggNodes.values());const updateEggs=()=>{for(const rule of eggRules){const unlocked=rule.names.some(name=>footprint.visited.has(stationIdByName.get(name))),image=eggNodes.get(rule.id),wasUnlocked=image.classList.contains("unlocked");image.hidden=!unlocked;image.classList.toggle("unlocked",unlocked);if(unlocked&&!wasUnlocked&&!reduceMotion){image.classList.remove("just-unlocked");requestAnimationFrame(()=>image.classList.add("just-unlocked"))}}};
 const updateSummary=()=>{$("#station-count").textContent=hotspots.stationHotspots.length;updateEggs();renderStatistics(network)};const hf=document.createDocumentFragment();
 for(const h of hotspots.segmentHotspots){const s=segmentById.get(h.segmentId),line=lineById.get(h.lineId);if(!s||!line)continue;const fromId=lsById.get(s.fromLineStationId).stationId,toId=lsById.get(s.toLineStationId).stationId,from=stationById.get(fromId),to=stationById.get(toId),a=pointByStationId.get(fromId),b=pointByStationId.get(toId),g=el("g",{class:`segment-node ${footprint.ridden.has(h.segmentId)?"ridden":"unridden"}`,tabindex:"0",role:"button","aria-pressed":String(footprint.ridden.has(h.segmentId)),"aria-label":`${line.nameZh}，${from.nameZh}至${to.nameZh}`});g.append(el("path",{d:h.path,class:"network-segment segment-visible",stroke:h.stroke||line.color,"stroke-width":5}),el("path",{d:h.path,class:"segment-hit-area","stroke-width":h.hitWidth||12}));let handle=null;const change=()=>{recordHistory();toggle(footprint.ridden,h.segmentId);const done=footprint.ridden.has(h.segmentId);g.classList.toggle("ridden",done);g.classList.toggle("unridden",!done);g.setAttribute("aria-pressed",String(done));handle?.classList.toggle("ridden",done);saveFootprint();updateSummary()};interactive(g,`${from.nameZh} — ${to.nameZh}`,()=>`${line.nameZh} · ${footprint.ridden.has(h.segmentId)?"已乘坐":"未乘坐"}`,change);if(a&&b&&Math.hypot(b.x-a.x,b.y-a.y)<26){handle=el("circle",{class:`short-segment-handle ${footprint.ridden.has(h.segmentId)?"ridden":""}`,cx:(a.x+b.x)/2,cy:(a.y+b.y)/2,r:9,tabindex:"0",role:"button","aria-label":`${line.nameZh}，${from.nameZh}至${to.nameZh}`});interactive(handle,`${from.nameZh} — ${to.nameZh}`,()=>`${line.nameZh} · ${footprint.ridden.has(h.segmentId)?"已乘坐":"未乘坐"}`,change);hf.append(handle)}sf.append(g)}segments.replaceChildren(sf);handles.replaceChildren(hf);
 const tf=document.createDocumentFragment();
 for(const p of hotspots.stationHotspots){const station=stationById.get(p.stationId);if(!station)continue;const served=[...(stationLines.get(p.stationId)?.values()||[])],g=el("g",{class:`station-node ${p.symbol.replaceAll("_","-")} ${footprint.visited.has(p.stationId)?"visited":"unvisited"}`,transform:`translate(${p.x} ${p.y})`,tabindex:"0",role:"button","aria-pressed":String(footprint.visited.has(p.stationId)),"aria-label":`${station.nameZh}，${served.map(x=>x.nameZh).join("、")}`});g.append(el("circle",{class:"station-hit-area",r:13}));if(p.symbol==="out_of_station_transfer")g.append(el("circle",{class:"station-halo transfer-outer",r:10}),el("circle",{class:"station-halo transfer-inner",r:5.5}));else if(p.symbol==="in_station_transfer")g.append(el("circle",{class:"station-halo transfer-outer",r:9}),el("circle",{class:"station-dot transfer-core",r:3}));else g.append(el("circle",{class:"station-halo",r:5}),el("circle",{class:"station-dot",r:1.35}));const label=el("text",{class:"station-label",x:8,y:-7,"text-anchor":"start"});label.textContent=station.nameZh;g.append(label);const transfer=p.symbol==="out_of_station_transfer"?" · 出站换乘":p.symbol==="in_station_transfer"?" · 站内换乘":"";interactive(g,station.nameZh,()=>`${served.map(x=>x.nameZh).join(" · ")}${transfer} · ${footprint.visited.has(p.stationId)?"已到访":"未到访"}`,()=>{recordHistory();const wasVisited=footprint.visited.has(p.stationId);toggle(footprint.visited,p.stationId);if(wasVisited)footprint.visitTypes.delete(p.stationId);else footprint.visitTypes.set(p.stationId,defaultVisitTypes(p.stationId));g.classList.toggle("visited",footprint.visited.has(p.stationId));g.classList.toggle("unvisited",!footprint.visited.has(p.stationId));g.setAttribute("aria-pressed",String(footprint.visited.has(p.stationId)));saveFootprint();updateSummary()});tf.append(g)}stations.replaceChildren(tf);
 $("#line-count").textContent=network.lines.length;$("#effective-date").textContent=network.meta.effectiveDate;$("#map-summary").hidden=false;$(".symbol-legend").hidden=false;status.classList.add("ready");updateSummary();loading.classList.add("done");if(!preserveView)requestAnimationFrame(()=>fit(hotspots.coordinateSystem.width,hotspots.coordinateSystem.height));else applyView()
}
stage.addEventListener("wheel",e=>{e.preventDefault();zoomAt(screenPoint(e),Math.exp(-e.deltaY*.0015))},{passive:false});stage.addEventListener("dblclick",e=>zoomAt(screenPoint(e),1.7));stage.addEventListener("click",()=>{tooltip.hidden=true});
stage.addEventListener("pointerdown",e=>{if(e.target.closest?.(".station-node,.segment-node,.short-segment-handle"))return;stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,screenPoint(e));stage.classList.add("dragging");if(pointers.size===1)dragStart={point:screenPoint(e),view:{...view}};if(pointers.size===2){const[a,b]=[...pointers.values()];pinchStart={distance:Math.hypot(b.x-a.x,b.y-a.y),scale:view.scale}}});
stage.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,screenPoint(e));if(pointers.size===1&&dragStart){const p=screenPoint(e);view.x=dragStart.view.x+p.x-dragStart.point.x;view.y=dragStart.view.y+p.y-dragStart.point.y;applyView()}else if(pointers.size===2&&pinchStart){const[a,b]=[...pointers.values()],d=Math.hypot(b.x-a.x,b.y-a.y);zoomAt({x:(a.x+b.x)/2,y:(a.y+b.y)/2},(pinchStart.scale*d/pinchStart.distance)/view.scale)}});
function release(e){pointers.delete(e.pointerId);dragStart=null;pinchStart=null;if(!pointers.size)stage.classList.remove("dragging")}stage.addEventListener("pointerup",release);stage.addEventListener("pointercancel",release);$("#zoom-in").addEventListener("click",()=>zoomAt({x:map.clientWidth/2,y:map.clientHeight/2},1.35));$("#zoom-out").addEventListener("click",()=>zoomAt({x:map.clientWidth/2,y:map.clientHeight/2},1/1.35));$("#reset-view").addEventListener("click",()=>{view={...initial};applyView()});
const modeButton=$("#interaction-mode");modeButton.addEventListener("click",()=>{const enabled=!map.classList.contains("segment-pick-mode");map.classList.toggle("segment-pick-mode",enabled);if(enabled)viewport.append(segments,handles);else viewport.insertBefore(segments,stations);modeButton.setAttribute("aria-pressed",String(enabled));modeButton.textContent=enabled?"车站点选":"区间点选";modeButton.title=enabled?"当前为区间点选模式；点击切回车站点选":"开启后可点选被车站遮挡的区间";tooltip.hidden=true});
function setFileStatus(message,type=""){const node=$("#file-status");node.textContent=message;node.className=type}
function loadRecord(record,{imported=false}={}){currentRecord=record;footprint={ridden:new Set(record.selectedSegmentIds||[]),visited:new Set((record.stationVisits||[]).map(x=>x.stationId)),visitTypes:new Map((record.stationVisits||[]).map(x=>[x.stationId,x.visitTypes]))};historyPast=imported?[{ridden:[],visited:[],visitTypes:[]}]:[];historyFuture=[];updateHistoryButtons();localStorage.setItem(ACTIVE_KEY,record.id);localStorage.removeItem(FOOTPRINT_KEY);if(currentNetwork&&currentHotspots)render(currentNetwork,currentHotspots)}
async function refreshFootprintSelect(){const records=await listFootprints(),select=$("#footprint-select");select.replaceChildren(...records.map(record=>{const option=document.createElement("option");option.value=record.id;option.textContent=record.title;option.selected=record.id===currentRecord?.id;return option}))}
async function initializeFootprints(){let records=await listFootprints(),active=localStorage.getItem(ACTIVE_KEY),record=records.find(x=>x.id===active)||records[0];if(!record){record={id:newId(),title:"我的足迹",createdAt:now(),updatedAt:now(),selectedSegmentIds:[...footprint.ridden],stationVisits:[...footprint.visited].map(stationId=>({stationId,visitTypes:["board_or_alight"]}))};await putFootprint(record)}loadRecord(record);await refreshFootprintSelect()}
function safeName(value){return(value||"footprint").replace(/[\\/:*?"<>|]/g,"-").slice(0,80)}
function exportWarning(file){const result=validateBeforeExport(file,currentNetwork);if(!result.valid){alert(`导出已阻止：\n${result.errors.join("\n")}`);setFileStatus(`导出校验失败：${result.errors[0]}`,"error");return false}if(!result.warnings.length)return true;const sections=result.warnings.map(warning=>warning.code==="continuous_endpoint_not_visited"?`连续区间到访校验（${warning.items.length}项）：\n${warning.items.slice(0,30).map(x=>x.kind==="closed_loop_without_visit"?`${x.groupName}：闭合区间内未选择任何到访车站`:`${x.groupName}：端点站 ${x.stationName} 未选中`).join("\n")}${warning.items.length>30?"\n……":""}`:`不邻接已乘区间的到访车站（${warning.items.length}站）：\n${warning.items.slice(0,20).join("、")}${warning.items.length>20?"……":""}`);return confirm(`${sections.join("\n\n")}\n\n这些记录不会被自动修改。是否仍然导出？`)}
function blobDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error||new Error("图片编码失败"));reader.readAsDataURL(blob)})}
async function embedExportImages(clone){for(const image of clone.querySelectorAll("image.easter-egg.unlocked")){const href=image.getAttribute("href");if(!href)continue;const response=await fetch(new URL(href,document.baseURI));if(!response.ok)throw new Error(`彩蛋图片读取失败：HTTP ${response.status}`);image.setAttribute("href",await blobDataUrl(await response.blob()))}}
async function exportSvg({includeEggs=true}={}){const file=recordFile();if(!exportWarning(file))return;const clone=map.cloneNode(true),vp=clone.querySelector("#map-viewport"),size=currentHotspots.coordinateSystem;vp.removeAttribute("transform");clone.setAttribute("viewBox",`0 0 ${size.width} ${size.height}`);clone.setAttribute("width",size.width);clone.setAttribute("height",size.height);clone.querySelectorAll(".station-label").forEach(x=>x.setAttribute("style","opacity:1"));if(includeEggs)await embedExportImages(clone);else clone.querySelectorAll("image.easter-egg").forEach(image=>image.remove());const css=[...document.styleSheets].flatMap(sheet=>{try{return[...sheet.cssRules].map(rule=>rule.cssText)}catch{return[]}}).join("\n"),style=document.createElementNS(NS,"style");style.textContent=css;clone.prepend(style);return{svg:`<?xml version="1.0" encoding="UTF-8"?>\n${new XMLSerializer().serializeToString(clone)}`,file}}
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error(`图片加载失败：${src}`));image.src=src})}
async function pngEggImages(){return Promise.all([...eggs.querySelectorAll("image.easter-egg.unlocked")].map(async node=>({image:await loadImage(new URL(node.getAttribute("href"),document.baseURI).href),x:Number(node.getAttribute("x")),y:Number(node.getAttribute("y")),width:Number(node.getAttribute("width")),height:Number(node.getAttribute("height"))})))}
$("#footprint-select").addEventListener("change",async e=>{await flushPendingSave();const record=await getFootprint(e.target.value);if(record){loadRecord(record);setFileStatus(`已切换到“${record.title}”`,"success")}});
$("#new-footprint").addEventListener("click",async()=>{const title=prompt("新足迹名称","我的新足迹");if(!title?.trim())return;await flushPendingSave();const record={id:newId(),title:title.trim().slice(0,100),createdAt:now(),updatedAt:now(),selectedSegmentIds:[],stationVisits:[]};await putFootprint(record);loadRecord(record);await refreshFootprintSelect();setFileStatus("已新建足迹","success")});
$("#rename-footprint").addEventListener("click",async()=>{const title=prompt("足迹名称",currentRecord.title);if(!title?.trim())return;await flushPendingSave();currentRecord={...currentRecord,title:title.trim().slice(0,100),updatedAt:now()};await putFootprint(currentRecord);await refreshFootprintSelect();setFileStatus("已重命名","success")});
$("#copy-footprint").addEventListener("click",async()=>{await flushPendingSave();const copy={...recordFile(),id:newId(),title:`${currentRecord.title}（副本）`.slice(0,100),createdAt:now(),updatedAt:now()};await putFootprint(copy);loadRecord(copy);await refreshFootprintSelect();setFileStatus("已创建副本","success")});
$("#delete-footprint").addEventListener("click",async()=>{const records=await listFootprints();if(records.length===1){setFileStatus("至少保留一份足迹","error");return}if(!confirm(`确定删除“${currentRecord.title}”吗？此操作无法撤销。`))return;await flushPendingSave();const id=currentRecord.id;await deleteFootprint(id);const next=(await listFootprints())[0];loadRecord(next);await refreshFootprintSelect();setFileStatus("足迹已删除","success")});
$("#import-json").addEventListener("click",()=>$("#import-file").click());$("#import-file").addEventListener("change",async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{const data=JSON.parse(await file.text()),result=validateImport(data,currentNetwork);if(result.errors.length){setFileStatus(result.errors.join("；"),"error");alert(`导入失败：\n${result.errors.join("\n")}`);return}const summary=`将作为新足迹导入“${result.clean.title}”\n区间：${result.clean.selectedSegmentIds.length}\n到访车站：${result.clean.stationVisits.length}${result.ignored.length?`\n忽略/无法映射：${result.ignored.length}\n${result.ignored.slice(0,15).join("\n")}`:""}`;if(!confirm(`${summary}\n\n确认导入？`))return;await flushPendingSave();const record={...result.clean,id:newId(),createdAt:result.clean.createdAt||now(),updatedAt:now()};await putFootprint(record);loadRecord(record,{imported:true});await refreshFootprintSelect();setFileStatus("导入成功，已创建新足迹；可撤销为清空状态","success")}catch(error){setFileStatus("JSON 文件无法解析","error");alert(`导入失败：${error.message}`)}});
function undo(){if(!historyPast.length)return;historyFuture.push(snapshotState());restoreState(historyPast.pop());refreshAfterStateChange();setFileStatus("已撤销","success")}
function redo(){if(!historyFuture.length)return;historyPast.push(snapshotState());restoreState(historyFuture.pop());refreshAfterStateChange();setFileStatus("已重做","success")}
function changeWholeLine(select){const lineId=$("#bulk-line-select").value,line=currentNetwork.lines.find(x=>x.id===lineId),ids=currentNetwork.segments.filter(x=>x.lineId===lineId).map(x=>x.id),changes=ids.filter(id=>footprint.ridden.has(id)!==select);if(!changes.length){setFileStatus(select?"该线路已经全部标记":"该线路已经全部取消");return}if(select&&!confirm(`将${line.nameZh}的 ${ids.length} 个运营区间全部设为已乘，是否继续？`))return;recordHistory();for(const id of ids)select?footprint.ridden.add(id):footprint.ridden.delete(id);refreshAfterStateChange();setFileStatus(`${line.nameZh}已${select?"整线标记":"整线取消"}`,"success")}
$("#undo-action").addEventListener("click",undo);$("#redo-action").addEventListener("click",redo);$("#select-line").addEventListener("click",()=>changeWholeLine(true));$("#unselect-line").addEventListener("click",()=>changeWholeLine(false));
$("#clear-footprint").addEventListener("click",()=>{if(!footprint.ridden.size&&!footprint.visited.size){setFileStatus("当前足迹已经为空");return}if(!confirm(`确定清空“${currentRecord.title}”的全部区间和到访车站吗？可使用撤销恢复。`))return;recordHistory();footprint={ridden:new Set(),visited:new Set(),visitTypes:new Map()};refreshAfterStateChange();setFileStatus("足迹已清空，可撤销恢复","success")});
document.addEventListener("keydown",e=>{if(!(e.ctrlKey||e.metaKey)||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}else if(e.key.toLowerCase()==="y"){e.preventDefault();redo()}});
$("#export-json").addEventListener("click",()=>{const file=recordFile();if(!exportWarning(file))return;downloadBlob(new Blob([JSON.stringify(file,null,2)],{type:"application/json"}),`${safeName(file.title)}.json`);setFileStatus("JSON 已导出","success")});
$("#export-svg").addEventListener("click",async()=>{try{const result=await exportSvg();if(!result)return;downloadBlob(new Blob([result.svg],{type:"image/svg+xml"}),`${safeName(result.file.title)}.svg`);setFileStatus("SVG 已导出","success")}catch(error){console.error(error);setFileStatus(`SVG 生成失败：${error.message}`,"error")}});
$("#export-png").addEventListener("click",async()=>{let url;try{const result=await exportSvg({includeEggs:false});if(!result)return;const eggImages=await pngEggImages();url=URL.createObjectURL(new Blob([result.svg],{type:"image/svg+xml"}));const image=await loadImage(url),canvas=document.createElement("canvas"),scale=2;canvas.width=currentHotspots.coordinateSystem.width*scale;canvas.height=currentHotspots.coordinateSystem.height*scale;const context=canvas.getContext("2d");context.fillStyle="#f7f5ef";context.fillRect(0,0,canvas.width,canvas.height);context.scale(scale,scale);context.drawImage(image,0,0);for(const egg of eggImages)context.drawImage(egg.image,egg.x,egg.y,egg.width,egg.height);canvas.toBlob(blob=>{if(!blob){setFileStatus("PNG 生成失败","error");return}downloadBlob(blob,`${safeName(result.file.title)}.png`);setFileStatus("PNG 已导出","success")},"image/png")}catch(error){console.error(error);setFileStatus(`PNG 生成失败：${error.message}`,"error")}finally{if(url)URL.revokeObjectURL(url)}});
$("#export-excel").addEventListener("click",()=>{try{const file=recordFile();if(!exportWarning(file))return;downloadBlob(buildXlsxBlob(currentNetwork,file),`${safeName(file.title)}.xlsx`);setFileStatus("Excel 报告已导出","success")}catch(error){console.error(error);setFileStatus(`Excel 报告生成失败：${error.message}`,"error")}});
try{const[nr,hr]=await Promise.all([fetch("./data/network.json"),fetch("./data/diagram-hotspots.json")]);if(!nr.ok||!hr.ok)throw new Error(`HTTP ${nr.status}/${hr.status}`);const[network,hotspots]=await Promise.all([nr.json(),hr.json()]);if(hotspots.status!=="ready")throw new Error(`热点数据状态为 ${hotspots.status}`);currentNetwork=network;currentHotspots=hotspots;$("#bulk-line-select").replaceChildren(...network.lines.map(line=>{const option=document.createElement("option");option.value=line.id;option.textContent=line.nameZh;return option}));await initializeFootprints();render(network,hotspots);updateHistoryButtons()}catch(error){console.error(error);status.classList.add("error");status.lastElementChild.textContent="SVG 热点数据读取失败";loading.querySelector("p").textContent="无法读取正式线网热点数据，请检查 diagram-hotspots.json。"}
