import { calculateMileageM } from "./mileage.js";

export function geoDistanceKm(a,b){const rad=x=>x*Math.PI/180,R=6371,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(q))}

export function calculateStatistics(network,state){
 const riddenIds=state.selectedSegmentIds||[],visits=state.stationVisits||[],riddenSet=new Set(riddenIds),visitedIds=new Set(visits.map(x=>x.stationId)),stationById=new Map(network.stations.map(x=>[x.id,x])),lineStationById=new Map(network.lineStations.map(x=>[x.id,x])),visited=visits.map(x=>stationById.get(x.stationId)).filter(Boolean),mileageM=calculateMileageM(network,riddenIds),totalMileageM=calculateMileageM(network,network.segments.map(x=>x.id));
 const lines=network.lines.map((line,index)=>{const segments=network.segments.filter(x=>x.lineId===line.id),stationIds=[...new Set(network.lineStations.filter(x=>x.lineId===line.id).map(x=>x.stationId))],segmentCount=segments.filter(x=>riddenSet.has(x.id)).length,stationCount=stationIds.filter(x=>visitedIds.has(x)).length;return{line,index,segmentCount,segmentTotal:segments.length,segmentRate:segments.length?segmentCount/segments.length:0,stationCount,stationTotal:stationIds.length,stationRate:stationIds.length?stationCount/stationIds.length:0,participated:segmentCount>0,complete:segments.length>0&&segmentCount===segments.length}});
 const districts=network.districts.map(district=>{const stations=network.stations.filter(x=>x.districtIds.includes(district.id)),count=stations.filter(x=>visitedIds.has(x.id)).length;return{district,count,total:stations.length,rate:stations.length?count/stations.length:0}}),visitedDistrictIds=new Set(visited.flatMap(x=>x.districtIds));
 const transferStationIds=new Set(network.transferLinks.flatMap(link=>[lineStationById.get(link.fromLineStationId)?.stationId,lineStationById.get(link.toLineStationId)?.stationId]).filter(Boolean)),visitedTransfers=visited.filter(x=>transferStationIds.has(x.id)).length,completedLines=lines.filter(x=>x.complete),participatedLines=lines.filter(x=>x.participated);
 const points={mileage:Math.round(mileageM/1000),stations:visited.length,transfers:visitedTransfers,districts:visitedDistrictIds.size*4,lines:completedLines.length*10};points.total=points.mileage+points.stations+points.transfers+points.districts+points.lines;
 const located=visited.filter(x=>x.coordinate),extreme=(key,mode)=>{if(!located.length)return{value:null,stations:[]};const value=Math[mode](...located.map(x=>x.coordinate[key]));return{value,stations:located.filter(x=>x.coordinate[key]===value).sort((a,b)=>a.id.localeCompare(b.id))}},north=extreme("lat","max"),south=extreme("lat","min"),east=extreme("lng","max"),west=extreme("lng","min");
 const maxSegmentCount=Math.max(0,...lines.map(x=>x.segmentCount)),topLines=lines.filter(x=>maxSegmentCount>0&&x.segmentCount===maxSegmentCount),maxStationCount=Math.max(0,...lines.map(x=>x.stationCount)),topStationLines=lines.filter(x=>maxStationCount>0&&x.stationCount===maxStationCount),maxDistrictCount=Math.max(0,...districts.map(x=>x.count)),topDistricts=districts.filter(x=>maxDistrictCount>0&&x.count===maxDistrictCount);
 return{riddenIds,visitedIds,visited,mileageM,totalMileageM,lines,districts,visitedDistrictIds,transferStationIds,visitedTransfers,completedLines,participatedLines,points,extremes:{north,south,east,west,northSouthKm:north.stations[0]&&south.stations[0]?geoDistanceKm(north.stations[0].coordinate,south.stations[0].coordinate):null,eastWestKm:east.stations[0]&&west.stations[0]?geoDistanceKm(east.stations[0].coordinate,west.stations[0].coordinate):null},topLines,topStationLines,topDistricts};
}
